spring:
  output:
    ansi:
      enabled: always

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:hi-namaste
    username: sa
    password:
    driver-class-name: org.h2.Driver