spring:
  datasource:
    url: jdbc:h2:mem:hi-namaste
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: always